src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CartRepository::class)
 */
class Cart
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\OneToMany(targetEntity=CartItem::class, mappedBy="cart")
     */
    private $cartItems;

    public function __construct()
    {
        $this->cartItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection|CartItem[]
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): self
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems[] = $cartItem;
            $cartItem->setCart($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): self
    {
        if ($this->cartItems->contains($cartItem)) {
            $this->cartItems->removeElement($cartItem);
            // set the owning side to null (unless already changed)
            if ($cartItem->getCart() === $this) {
                $cartItem->setCart(null);
            }
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=ProductCategory::class, inversedBy="products")
     */
    private $product_category;

    /**
     * @ORM\OneToMany(targetEntity=CartItem::class, mappedBy="product")
     */
    private $cartItems;

    public function __construct()
    {
        $this->cartItems = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->product_category;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getProductCategory(): ?ProductCategory
    {
        return $this->product_category;
    }

    public function setProductCategory(?ProductCategory $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    /**
     * @return Collection|CartItem[]
     */
    public function getCartItems(): Collection
    {
        return $this->cartItems;
    }

    public function addCartItem(CartItem $cartItem): self
    {
        if (!$this->cartItems->contains($cartItem)) {
            $this->cartItems[] = $cartItem;
            $cartItem->setProduct($this);
        }

        return $this;
    }

    public function removeCartItem(CartItem $cartItem): self
    {
        if ($this->cartItems->contains($cartItem)) {
            $this->cartItems->removeElement($cartItem);
            // set the owning side to null (unless already changed)
            if ($cartItem->getProduct() === $this) {
                $cartItem->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\CartItem;
use App\Repository\CartRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    private $user_cart_id;
    private $cart;

    public function __construct(CartRepository $cart)
    {
        $this->cart = $cart;
        $this->user_cart_id = $cart->getUserCartId();
    }

    /**
     * List all Cart Items
     * @Route("shop/cart", methods="GET", name="cart")
     */
    public function index()
    {

        $cart_total = $this->cart->getCartTotal($this->user_cart_id);
        $cart_items = $this->cart->getCartItems($this->user_cart_id);

        return $this->render('cart/index.html.twig', [
            'cart_total' => $cart_total,
            'cart_items' => $cart_items,
        ]);
    }


    /**
     * Add or Update Cart Item
     *
     * @Route("shop/cart/add", methods="POST", name="add_to_cart")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request, CartRepository $cart, ProductRepository $product): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        //get product id
        $product_id = $request->get('product_id');
        //find the product
        $product = $product->find($product_id);
        $new_quantity = 1;

        $user_id = 1; //TODO set logged user id
        //check user has a cart
        $user_cart = $cart->findOneBy(['user_id' => $user_id]);
        if (!$user_cart) {
            //if not create a new user cart
            $user_cart = new Cart();
            $user_cart->setUserId(1);
            $entityManager->persist($user_cart);
            $entityManager->flush();
        }

        //check product is already in the cart
        $cart_items_arr = $user_cart->getCartItems()->filter(function (CartItem $item) use ($product_id) {
            return $item->getProduct()->getId() == $product_id;
        });

        //if product in the cart update the current quantity
        if (count($cart_items_arr)) {
            $cart_item = $cart_items_arr->first();
            $old_quantity = $cart_item->getQuantity();
            $new_quantity = $old_quantity + 1;
            $cart_item->setQuantity($new_quantity);
        } else {
            //if product not in the cart add new item
            $cart_item = new CartItem();
            $cart_item->setQuantity($new_quantity);
            $cart_item->setProduct($product);
            $cart_item->setCart($user_cart);
            $user_cart->addCartItem($cart_item);
        }

        $entityManager->persist($cart_item);
        $entityManager->flush();

        return $this->redirectToRoute('cart');
    }

    /**
     * Deletes a Cart Item.
     *
     * @Route("shop/cart/{id}/delete", methods="POST", name="cart_item_delete")
     */
    public function delete(Request $request, CartItem $cart_item)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($cart_item);
        $entityManager->flush();
        return new JsonResponse(['type' => 'success']);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Your Cart{% endblock %}

{% block body %}
    <section class="mt-3">
        {{ include('inc/_cart_total.html.twig') }}
        <div class="row">
            <div class="col-12">
                {% if cart_items %}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Item Category</th>
                            <th scope="col" class="text-right">Item Price</th>
                            <th scope="col" class="text-right">Quantity</th>
                            <th scope="col" class="text-right">Total</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cart_item in cart_items %}
                            <tr class="">
                                <td>{{ cart_item.product.name }}</td>
                                <td>{{ cart_item.product.productCategory }}</td>
                                <td class="text-right">{{ cart_item.product.price|number_format(2, '.', ',') }}</td>
                                <td class="text-right">{{ cart_item.quantity }}</td>
                                {% set unit_price = cart_item.product.price * cart_item.quantity %}
                                <td class="text-right">{{ unit_price|number_format(2, '.', ',') }}</td>
                                <td>
                                    <button type="button" class="btn btn-sm btn-outline-danger delete" data-url="{{ url('cart_item_delete', {id: cart_item.id}) }}">Delete</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h4>No products in cart</h4>
                {% endif %}
            </div>
    </section>
{% endblock %}